name: bier_env
channels:
  - esri
  - anaconda
  - defaults
dependencies:
  - python=3.11
  - arcgis
  - python-dotenv
  - pip
  - pip:
    - "--editable=git+https://github.com/bcgov/geobc-bier.git#egg=bier&subdirectory=bier"
