name: GeoHub COP Credentials Check

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: bier_env
        python-version: 3.11

    - name: Install dependencies
      shell: bash
      run: |
        conda env update --file AGO-Admin/Credentials-Check/requirements.yaml --name bier_env
        conda env list
        conda init bash
        . ~/.bashrc
        conda activate bier_env
        
    - name: Run script
      shell: bash
      env:
        AGO_PORTAL_URL: ${{secrets.AGO_PORTAL_URL}}
        AGO_USER: ${{secrets.COPUSER_USER}}
        AGO_PASS: ${{secrets.COPUSER_PASS}}
        BIER_TEAMS_WEBHOOK: ${{secrets.BIER_TEAMS_WEBHOOK}}

      run: |
        # you may have to activate the environment before running the 
        # python script, and you likley need to say python3 vs just python
        conda init bash
        . ~/.bashrc
        conda activate bier_env
        python3 AGO-Admin/Credentials-Check/AGO_Credentials_Check.py
