name: GeoHub COP Credentials Check

on:
  workflow_dispatch:
    
jobs:
  setup-python:
    uses: ./.github/workflows/setup-python-env.yml
    
  use-python-env:
    needs: setup-python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore virtual environment
        uses: actions/cache@v4
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Use Python Environment
        run: |
          source venv/bin/activate
          python AGO-Admin/Credentials-Check/AGO_Credentials_Check.py  # Run your script
        env:
          AGO_PORTAL_URL: ${{secrets.AGO_PORTAL_URL}}
          AGO_USER: ${{secrets.COPUSER_USER}}
          AGO_PASS: ${{secrets.COPUSER_PASS}}
          BIER_TEAMS_WEBHOOK: ${{secrets.BIER_TEAMS_WEBHOOK}}
